name: auto tag

on:
  pull_request_target:
    types: [opened, synchronize, closed]
    paths:
      - "debian/changelog"

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  auto_tag:
    uses: tsic404/deepin-community.github/.github/workflows/auto-tag.yml@auto-tag-fix
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
