name: auto tag

on:
  pull_request_target:
    types: [opened, synchronize, closed]
    paths:
      - "debian/changelog"

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: get changelog version
        id: get-version
        run: |
          echo "::set-output name=TAG::$(LC_ALL=C dpkg-parsechangelog -S Version)"

      - name: check tag exsits
        id: test-tag-exists
        run: |
          echo "::set-output name=EXISTS::$(git tag -l ${{steps.get-version.outputs.TAG}} == ${{steps.get-version.outputs.TAG}})"

      - name: create comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const BOT_NAME = "TAG Bot"
            const COMMENT_HEAD = "**" + BOT_NAME + "**\n"
            const COMMENT_BODY = "TAG: ${{ steps.get-version.outputs.TAG }}\nTAG_HAS_EXSIST: ${{ steps.test-tag-exists.outputs.EXISTS }}"
            const response = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })
            const reg = new RegExp("\\*+" + BOT_NAME + "\\*+")

            tagBotComment= response.data.find(comment => comment.body.match(reg))

            if (tagBotComment) {
              await github.rest.issues.updateComment({
                  comment_id: tagBotComment.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: COMMENT_HEAD + 'TAG: ${{ steps.get-version.outputs.TAG }}'
              })
            } else {
              await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: COMMENT_HEAD + 'TAG: ${{ steps.get-version.outputs.TAG }}'
              })
            }
