# daily trigger inner jenkins to build iso
name: call tag build
on:
  push:
    tags: "*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_job:
    uses: deepin-community/ci-test/.github/workflows/build-tag.yml@main
