name: auto tag

on:
  pull_request_target:
    types: [opened, synchronize, closed]
    paths:
      - "debian/changelog"

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    steps:
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: '${{ github.event.pull_request.user.login }}' # This is the input username

      - name: Get PR Author Email Address
        run: |
          echo "The name of the pusher: ${{ github.event.pull_request.user.login }}"
          echo "The email of the pusher: ${{ steps.test.outputs.email }}"
