name: auto tag

on:
  pull_request_target:
    types: [opened, synchronize, closed]
    paths:
      - "debian/changelog"

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Author Email Address
        run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"
