# daily trigger inner jenkins to build iso
name: tag build
on:
  push:
    tags: "*"

jobs:
  tag-build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}
      BRIDGE_TOKEN: ${{ secrets.BRIDGETOKEN }}

    steps:
      - name: export environment
        run: |
          export
