name: build deb
on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # disable uos
    if: ${{ github.repository == 'linuxdeepin/deepin-deb-installer' }}
    run: |
      echo ${{ github.repository }}
