name: build deb
on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # disable uos
    if: ${{ github.repository == 'deepin-community/ci-test' }}
    steps:
      - name: checkout_pull_request
        run: |
         echo ${{ github.repository }}
